
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: selfmanage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: selfmanage
      POSTGRES_USER: selfmanage
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U selfmanage -d selfmanage"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: